CREATE TABLE Empleados (
Nombre VARCHAR(30) NOT NULL,
DNI VARCHAR(9) PRIMARY KEY,
Sexo CHAR(1) CHECK (SEXO = 'M' OR SEXO = 'F'),
Categoria INTEGER(2),
Anyos INTEGER(3) CHECK (ANYOS >=0)
);

CREATE TABLE Nominas (
DNI VARCHAR(9) PRIMARY KEY,
Sueldo INTEGER,
CONSTRAINT DNI_FK FOREIGN KEY (DNI) REFERENCES Empleados(dni)
);

INSERT INTO Empleados VALUES ('James Cosling', '32000032G', 'M', 4, 7);
INSERT INTO Empleados VALUES ('Ada Lovelace', '32000031R', 'F', 1, 9);

INSERT INTO Nominas VALUES ('32000032G', 145000);
INSERT INTO Nominas VALUES ('32000031R', 95000);

