alter session set "_ORACLE_SCRIPT"=true;


CREATE TABLE Sueldos_Base (
Categoria NUMBER(2) CONSTRAINT CATEGORIA_CHECK CHECK (CATEGORIA >=1 AND CATEGORIA <=10) CONSTRAINT CATEGORIA_PK PRIMARY KEY, 
Sueldo_Base NUMBER CONSTRAINT CURSO_NT NOT NULL
);

CREATE TABLE Empleados (
Nombre VARCHAR(30) CONSTRAINT NOMBRE_NT NOT NULL,
DNI VARCHAR(9) CONSTRAINT DNI_EMPLEADOS_PK PRIMARY KEY,
Sexo CHAR(1) CONSTRAINT SEXO_CHECK CHECK (SEXO = 'M' OR SEXO = 'F'),
Categoria NUMBER(2),
Anyos NUMBER(3) CONSTRAINT ANYOS_CHECK CHECK (ANYOS >=0),
CONSTRAINT CATEGORIA_FK FOREIGN KEY (Categoria) REFERENCES Sueldos_Base(Categoria)
);

CREATE TABLE Nominas (
DNI VARCHAR(9) CONSTRAINT DNI_NOMINAS_PK PRIMARY KEY,
Sueldo NUMBER,
CONSTRAINT DNI_FK FOREIGN KEY (DNI) REFERENCES Empleados(DNI)
);

INSERT INTO Sueldos_Base VALUES (1, 50000);
INSERT INTO Sueldos_Base VALUES (2, 70000);
INSERT INTO Sueldos_Base VALUES (3, 90000);
INSERT INTO Sueldos_Base VALUES (4, 110000);
INSERT INTO Sueldos_Base VALUES (5, 130000);
INSERT INTO Sueldos_Base VALUES (6, 150000);
INSERT INTO Sueldos_Base VALUES (7, 170000);
INSERT INTO Sueldos_Base VALUES (8, 190000);
INSERT INTO Sueldos_Base VALUES (9, 210000);
INSERT INTO Sueldos_Base VALUES (10, 230000);

INSERT INTO Empleados VALUES ('James Cosling', '32000032G', 'M', 4, 7);
INSERT INTO Empleados VALUES ('Ada Lovelace', '32000031R', 'F', 1, 9);

INSERT INTO Nominas VALUES ('32000032G', 145000);
INSERT INTO Nominas VALUES ('32000031R', 95000);
